name: Backfill Brand SERPs

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start date (YYYY-MM-DD)"
        default: "2025-09-15"
        required: true
      end:
        description: "End date (YYYY-MM-DD, defaults to today)"
        required: false

jobs:
  backfill:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for rebase operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            # minimal deps for brand script
            python -m pip install pandas requests vaderSentiment
          fi

      - name: Backfill brand SERPs
        shell: bash
        env:
          START: ${{ github.e
