# .github/workflows/backfill_brand_articles.yml
name: Backfill Brand Articles

on:
  workflow_dispatch: {}

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run brand sentiment backfill
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in data/articles/*-articles.csv; do
            d="$(basename "$f" | cut -d- -f1-3)"
            echo ">> Aggregating $d from $f"
            python scripts/news_sentiment_brands.py --date "$d"
          done
      - name: Commit processed outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add -A
          git commit -m "backfill processed brand articles ($(date -u +%F))" || echo "No changes"
          git push
