name: Brand SERP Processing
# this is old and can probably be deleted. daily_brands.yml now handles this process
on:
  schedule:
    - cron: "0 16 * * *"   # 12:00 PM EDT
  workflow_dispatch:
    inputs:
      date:
        description: "Run date (YYYY-MM-DD, UTC). Leave blank for today."
        required: false

jobs:
  brand-serps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pandas requests vaderSentiment
          fi

      - name: Process brand SERPs
        shell: bash
        env:
          DATE_IN: ${{ github.event.inputs.date }}
        run: |
          set -euo pipefail
          DATE="${DATE_IN:-$(date -u +%F)}"
          ROW="data/serp_rows/${DATE}-brand-serps-rows.csv"
      
          # Optional idempotence – skip if we already wrote this date
          if [ -s "$ROW" ]; then
            echo "Rows already exist for ${DATE}; skipping."
            exit 0
          fi
      
          echo "Processing brand SERPs for ${DATE}"
          python scripts/process_serps_brands.py --date "${DATE}"


      # (leave your commit/push step as-is, or use the autostash version we added earlier)


      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Process brand SERPs for $(date -u +%F)" || echo "No changes"
          git push
