name: Brand SERP Processing

on:
  schedule:
    - cron: "10 9 * * *"   # keep your existing schedule (edit if you prefer)
  workflow_dispatch:
    inputs:
      date:
        description: "Run date (YYYY-MM-DD, UTC). Leave blank for today."
        required: false

jobs:
  brand-serps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pandas requests vaderSentiment
          fi

      # ⬇️ UPDATED: robust date selection + file existence guard
      - name: Process brand SERPs
        shell: bash
        env:
          DATE_IN: ${{ github.event.inputs.date }}
        run: |
          set -euo pipefail
          DATE="${DATE_IN:-$(date -u +%F)}"
          ROW="data/serp_rows/${DATE}-brand-serps-rows.csv"

          echo "Requested DATE: ${DATE}"
          if [ ! -f "$ROW" ]; then
            echo "No rows for ${DATE} at ${ROW} — trying yesterday (UTC)…"
            YDAY="$(date -u -d "${DATE} -1 day" +%F)"
            ROW="data/serp_rows/${YDAY}-brand-serps-rows.csv"
            if [ -f "$ROW" ]; then
              DATE="$YDAY"
              echo "Using yesterday: ${DATE}"
            else
              echo "Still not found. Trying latest available rows file…"
              latest=$(ls -1 data/serp_rows/*-brand-serps-rows.csv 2>/dev/null | sort | tail -n 1 || true)
              if [ -n "${latest}" ]; then
                DATE="$(basename "${latest}" | sed 's/-brand-serps-rows\.csv//')"
                ROW="$latest"
                echo "Using latest available date: ${DATE}"
              else
                echo "No brand SERP rows exist yet; skipping without error."
                exit 0
              fi
            fi
          fi

          echo "Processing brand SERPs for ${DATE}"
          python scripts/process_serps_brands.py --date "${DATE}"

      # (leave your commit/push step as-is, or use the autostash version we added earlier)


      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Process brand SERPs for $(date -u +%F)" || echo "No changes"
          git push
