name: Daily CEO News Sentiment

on:
  schedule:
    - cron: "0 12 * * *"     # ~8am ET
  workflow_dispatch: {}
  push:
    paths:
      - 'news_sentiment_ceos.py'
      - 'ceo_aliases.csv'
      - 'ceos.txt'
      - '.github/workflows/daily_ceos.yml'

permissions:
  contents: write

# Prevent overlapping runs from racing on pushes
concurrency:
  group: repo-data-writes
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if requirements.txt exists)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure CEO data folders exist
        run: mkdir -p data_ceos/articles

      - name: Run daily CEO sentiment
        run: python news_sentiment_ceos.py

     - name: Commit & push changes (if any)
  run: |
    set -e
    git config user.name  "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Only commit if something actually changed
    if [[ -n "$(git status --porcelain)" ]]; then
      git add -A
      git commit -m "chore(data): update $(date -u +%F)"

      # Reconcile with remote even if we have local changes
      git pull --rebase --autostash origin main

      # Push our rebased commit
      git push origin HEAD:main
    else
      echo "No changes to commit."
    fi
