name: Daily Brands Articles

on:
  schedule:
    - cron: "30 7 * * *"   # 07:30 UTC daily (adjust as you like)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 vaderSentiment

      - name: Fetch brand headlines
        run: python news_articles_brands.py

      - name: Aggregate brand news sentiment
        run: python news_sentiment_brands.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update brand articles & daily counts for $(date -u +%F)" || echo "No changes"
          git push
