name: Daily CEO News Sentiment

on:
  schedule:
    - cron: "0 12 * * *"   # ~8am ET
  workflow_dispatch:

permissions:
  contents: write

# Prevent overlapping runs
concurrency:
  group: daily-ceos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      TZ: America/New_York

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas requests feedparser vaderSentiment

      - name: Ensure folders (NEW STRUCTURE)
        run: |
          mkdir -p data/daily_counts
          mkdir -p data/processed_articles
          mkdir -p data/processed_serps
          mkdir -p rosters

      # Build today's articles → data/processed_articles/YYYY-MM-DD-ceo-articles-modal.csv
      - name: Build daily CEO articles (Google News RSS)
        env:
          ARTICLES_MAX_PER_ALIAS: "25"
          ARTICLES_SLEEP_SEC: "0.35"
          # ARTICLES_DATE: "YYYY-MM-DD"  # optional for backfills
        run: |
          python scripts/news_articles_ceos.py

      # Normalize daily counts and write to:
      # - data/processed_articles/{date}-ceo-articles-table.csv
      # - data/daily_counts/ceo-articles-daily-counts-chart.csv
      - name: Run daily CEO sentiment (counts)
        run: |
          python scripts/news_sentiment_ceos.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(ceos): update CEO counts & articles for $(date -u +%F)"
            git pull --rebase --autostash || true
            git push
          fi
