name: Daily CEO News Sentiment

on:
  schedule:
    - cron: "0 11 * * *"   # ~8am ET
  workflow_dispatch:

permissions:
  contents: write

# Prevent overlapping runs
concurrency:
  group: daily-ceos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      TZ: America/New_York

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas requests feedparser vaderSentiment

      - name: Ensure folders
        run: |
          mkdir -p data
          mkdir -p data_ceos
          mkdir -p data_ceos/articles
          mkdir -p data_ceos/serp_rows

      # Make sure aliases exist at data/ceo_aliases.csv
      - name: Ensure ceo_aliases at data/ceo_aliases.csv
        run: |
          if [ -f "data/ceo_aliases.csv" ]; then
            echo "Aliases already present."
          elif [ -f "data/serps/ceo_aliases.csv" ]; then
            cp -f "data/serps/ceo_aliases.csv" "data/ceo_aliases.csv"
            echo "Copied data/serps/ceo_aliases.csv -> data/ceo_aliases.csv"
          elif [ -f "ceo_aliases.csv" ]; then
            cp -f "ceo_aliases.csv" "data/ceo_aliases.csv"
            echo "Copied ceo_aliases.csv -> data/ceo_aliases.csv"
          else
            echo "WARNING: ceo_aliases.csv not found"
          fi

      # Build today's articles → data_ceos/articles/YYYY-MM-DD-articles.csv
      - name: Build daily CEO articles (Google News RSS)
        env:
          ARTICLES_MAX_PER_ALIAS: "25"
          ARTICLES_SLEEP_SEC: "0.35"
          # ARTICLES_DATE: "YYYY-MM-DD"  # optional for backfills
        run: |
          python news_articles_ceos.py

      # Normalize daily counts and write both data_ceos/<date>.csv and daily_counts.csv
      - name: Run daily CEO sentiment (counts)
        run: |
          python news_sentiment_ceos.py \
            --aliases data/ceo_aliases.csv \
            --articles-dir data_ceos/articles \
            --daily-dir data_ceos \
            --out data_ceos/daily_counts.csv

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(data_ceos): update CEO counts & articles for $(date -u +%F)"
            git pull --rebase --autostash || true
            git push
          fi
