name: Daily ROC News Sentiment

on:
  schedule:
    - cron: "0 12 * * *"   # ~8am ET during DST (12:00 UTC)
  workflow_dispatch: {}
  push:
    paths:
      - 'news_sentiment_roc.py'
      - 'requirements.txt'
      - 'roc_aliases.csv'
      - 'roc.txt'
      - 'roc-dashboard.html'
      - '.github/workflows/daily_roc.yml'

permissions:
  contents: write

# Prevent overlapping runs across workflows that write data
concurrency:
  group: repo-data-writes
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      TZ: America/New_York

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
