# DEPRECATED: This workflow is deprecated and disabled.
# SERP processing is now handled by:
# - daily_brands.yml (for brand SERPs)
# - daily_ceos.yml (for CEO SERPs) 
# - backfill_serps.yml (for historical backfills)
#
# This file is kept for reference only.
# To permanently remove, delete this file.

name: "[DEPRECATED] SERP Data"

on:
  # Disabled - remove schedule to prevent accidental runs
  # schedule:
  #   - cron: "45 6 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Deprecated workflow notice
        run: |
          echo "=========================================="
          echo "⚠️  THIS WORKFLOW IS DEPRECATED"
          echo "=========================================="
          echo ""
          echo "SERP processing is now handled by:"
          echo "  • daily_brands.yml (brand SERPs)"
          echo "  • daily_ceos.yml (CEO SERPs)"
          echo "  • backfill_serps.yml (historical)"
          echo ""
          echo "This workflow has been disabled to prevent"
          echo "duplicate processing and data conflicts."
          echo ""
          echo "To re-enable, update this file with correct"
          echo "paths matching the new data structure."
          echo "=========================================="
          exit 1
